/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeToMp4RouteImport } from './routes/youtube-to-mp4'
import { Route as YoutubeToMp3RouteImport } from './routes/youtube-to-mp3'
import { Route as YoutubeShortsDownloaderRouteImport } from './routes/youtube-shorts-downloader'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as R4kDownloaderRouteImport } from './routes/4k-downloader'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShortsIdRouteImport } from './routes/shorts.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const YoutubeToMp4Route = YoutubeToMp4RouteImport.update({
  id: '/youtube-to-mp4',
  path: '/youtube-to-mp4',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeToMp3Route = YoutubeToMp3RouteImport.update({
  id: '/youtube-to-mp3',
  path: '/youtube-to-mp3',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeShortsDownloaderRoute = YoutubeShortsDownloaderRouteImport.update({
  id: '/youtube-shorts-downloader',
  path: '/youtube-shorts-downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const R4kDownloaderRoute = R4kDownloaderRouteImport.update({
  id: '/4k-downloader',
  path: '/4k-downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsIdRoute = ShortsIdRouteImport.update({
  id: '/shorts/$id',
  path: '/shorts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/4k-downloader': typeof R4kDownloaderRoute
  '/blog': typeof BlogRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watch': typeof WatchRoute
  '/youtube-shorts-downloader': typeof YoutubeShortsDownloaderRoute
  '/youtube-to-mp3': typeof YoutubeToMp3Route
  '/youtube-to-mp4': typeof YoutubeToMp4Route
  '/blog/$slug': typeof BlogSlugRoute
  '/shorts/$id': typeof ShortsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/4k-downloader': typeof R4kDownloaderRoute
  '/blog': typeof BlogRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watch': typeof WatchRoute
  '/youtube-shorts-downloader': typeof YoutubeShortsDownloaderRoute
  '/youtube-to-mp3': typeof YoutubeToMp3Route
  '/youtube-to-mp4': typeof YoutubeToMp4Route
  '/blog/$slug': typeof BlogSlugRoute
  '/shorts/$id': typeof ShortsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/4k-downloader': typeof R4kDownloaderRoute
  '/blog': typeof BlogRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watch': typeof WatchRoute
  '/youtube-shorts-downloader': typeof YoutubeShortsDownloaderRoute
  '/youtube-to-mp3': typeof YoutubeToMp3Route
  '/youtube-to-mp4': typeof YoutubeToMp4Route
  '/blog/$slug': typeof BlogSlugRoute
  '/shorts/$id': typeof ShortsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/4k-downloader'
    | '/blog'
    | '/sitemap.xml'
    | '/watch'
    | '/youtube-shorts-downloader'
    | '/youtube-to-mp3'
    | '/youtube-to-mp4'
    | '/blog/$slug'
    | '/shorts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/4k-downloader'
    | '/blog'
    | '/sitemap.xml'
    | '/watch'
    | '/youtube-shorts-downloader'
    | '/youtube-to-mp3'
    | '/youtube-to-mp4'
    | '/blog/$slug'
    | '/shorts/$id'
  id:
    | '__root__'
    | '/'
    | '/4k-downloader'
    | '/blog'
    | '/sitemap.xml'
    | '/watch'
    | '/youtube-shorts-downloader'
    | '/youtube-to-mp3'
    | '/youtube-to-mp4'
    | '/blog/$slug'
    | '/shorts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R4kDownloaderRoute: typeof R4kDownloaderRoute
  BlogRoute: typeof BlogRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WatchRoute: typeof WatchRoute
  YoutubeShortsDownloaderRoute: typeof YoutubeShortsDownloaderRoute
  YoutubeToMp3Route: typeof YoutubeToMp3Route
  YoutubeToMp4Route: typeof YoutubeToMp4Route
  ShortsIdRoute: typeof ShortsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube-to-mp4': {
      id: '/youtube-to-mp4'
      path: '/youtube-to-mp4'
      fullPath: '/youtube-to-mp4'
      preLoaderRoute: typeof YoutubeToMp4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube-to-mp3': {
      id: '/youtube-to-mp3'
      path: '/youtube-to-mp3'
      fullPath: '/youtube-to-mp3'
      preLoaderRoute: typeof YoutubeToMp3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube-shorts-downloader': {
      id: '/youtube-shorts-downloader'
      path: '/youtube-shorts-downloader'
      fullPath: '/youtube-shorts-downloader'
      preLoaderRoute: typeof YoutubeShortsDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/4k-downloader': {
      id: '/4k-downloader'
      path: '/4k-downloader'
      fullPath: '/4k-downloader'
      preLoaderRoute: typeof R4kDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts/$id': {
      id: '/shorts/$id'
      path: '/shorts/$id'
      fullPath: '/shorts/$id'
      preLoaderRoute: typeof ShortsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R4kDownloaderRoute: R4kDownloaderRoute,
  BlogRoute: BlogRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WatchRoute: WatchRoute,
  YoutubeShortsDownloaderRoute: YoutubeShortsDownloaderRoute,
  YoutubeToMp3Route: YoutubeToMp3Route,
  YoutubeToMp4Route: YoutubeToMp4Route,
  ShortsIdRoute: ShortsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
