/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeToMp4RouteImport } from './routes/youtube-to-mp4'
import { Route as YoutubeToMp3RouteImport } from './routes/youtube-to-mp3'
import { Route as YoutubeShortsDownloaderRouteImport } from './routes/youtube-shorts-downloader'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as R4kDownloaderRouteImport } from './routes/4k-downloader'
import { Route as IndexRouteImport } from './routes/index'

const YoutubeToMp4Route = YoutubeToMp4RouteImport.update({
  id: '/youtube-to-mp4',
  path: '/youtube-to-mp4',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeToMp3Route = YoutubeToMp3RouteImport.update({
  id: '/youtube-to-mp3',
  path: '/youtube-to-mp3',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeShortsDownloaderRoute = YoutubeShortsDownloaderRouteImport.update({
  id: '/youtube-shorts-downloader',
  path: '/youtube-shorts-downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const R4kDownloaderRoute = R4kDownloaderRouteImport.update({
  id: '/4k-downloader',
  path: '/4k-downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/4k-downloader': typeof R4kDownloaderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/youtube-shorts-downloader': typeof YoutubeShortsDownloaderRoute
  '/youtube-to-mp3': typeof YoutubeToMp3Route
  '/youtube-to-mp4': typeof YoutubeToMp4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/4k-downloader': typeof R4kDownloaderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/youtube-shorts-downloader': typeof YoutubeShortsDownloaderRoute
  '/youtube-to-mp3': typeof YoutubeToMp3Route
  '/youtube-to-mp4': typeof YoutubeToMp4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/4k-downloader': typeof R4kDownloaderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/youtube-shorts-downloader': typeof YoutubeShortsDownloaderRoute
  '/youtube-to-mp3': typeof YoutubeToMp3Route
  '/youtube-to-mp4': typeof YoutubeToMp4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/4k-downloader'
    | '/sitemap.xml'
    | '/youtube-shorts-downloader'
    | '/youtube-to-mp3'
    | '/youtube-to-mp4'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/4k-downloader'
    | '/sitemap.xml'
    | '/youtube-shorts-downloader'
    | '/youtube-to-mp3'
    | '/youtube-to-mp4'
  id:
    | '__root__'
    | '/'
    | '/4k-downloader'
    | '/sitemap.xml'
    | '/youtube-shorts-downloader'
    | '/youtube-to-mp3'
    | '/youtube-to-mp4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R4kDownloaderRoute: typeof R4kDownloaderRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  YoutubeShortsDownloaderRoute: typeof YoutubeShortsDownloaderRoute
  YoutubeToMp3Route: typeof YoutubeToMp3Route
  YoutubeToMp4Route: typeof YoutubeToMp4Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube-to-mp4': {
      id: '/youtube-to-mp4'
      path: '/youtube-to-mp4'
      fullPath: '/youtube-to-mp4'
      preLoaderRoute: typeof YoutubeToMp4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube-to-mp3': {
      id: '/youtube-to-mp3'
      path: '/youtube-to-mp3'
      fullPath: '/youtube-to-mp3'
      preLoaderRoute: typeof YoutubeToMp3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube-shorts-downloader': {
      id: '/youtube-shorts-downloader'
      path: '/youtube-shorts-downloader'
      fullPath: '/youtube-shorts-downloader'
      preLoaderRoute: typeof YoutubeShortsDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/4k-downloader': {
      id: '/4k-downloader'
      path: '/4k-downloader'
      fullPath: '/4k-downloader'
      preLoaderRoute: typeof R4kDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R4kDownloaderRoute: R4kDownloaderRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  YoutubeShortsDownloaderRoute: YoutubeShortsDownloaderRoute,
  YoutubeToMp3Route: YoutubeToMp3Route,
  YoutubeToMp4Route: YoutubeToMp4Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
